inherit_from: .rubocop-todo.yml
require:
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'database_validations.gemspec'
  Exclude:
    - 'vendor/bundle/**/*'

Naming/FileName:
  Exclude:
    - 'example/Gemfile'
    - 'example/Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
