---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
services:
  - postgresql
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE database_validations_test;'
  - psql -U postgres -c 'CREATE DATABASE database_validations_test;'
script:
  - bundle exec rspec
  - bundle exec rubocop
