---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
services:
  - postgresql
  - mysql
before_install:
  - gem install bundler -v 1.16.4
  - mysql -u root -e 'CREATE DATABASE database_validations_test;'
  - psql -U postgres -c 'CREATE DATABASE database_validations_test;'
